HW6/WorldWideImporter/WorldWideImporter/Models/Person.cs
namespace WorldWideImporter.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Application.People")]
    public partial class Person
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Person()
        {
            Cities = new HashSet<City>();
            Countries = new HashSet<Country>();
            DeliveryMethods = new HashSet<DeliveryMethod>();
            PaymentMethods = new HashSet<PaymentMethod>();
            People1 = new HashSet<Person>();
            StateProvinces = new HashSet<StateProvince>();
            SystemParameters = new HashSet<SystemParameter>();
            TransactionTypes = new HashSet<TransactionType>();
            PurchaseOrderLines = new HashSet<PurchaseOrderLine>();
            PurchaseOrders = new HashSet<PurchaseOrder>();
            PurchaseOrders1 = new HashSet<PurchaseOrder>();
            SupplierCategories = new HashSet<SupplierCategory>();
            Suppliers = new HashSet<Supplier>();
            Suppliers1 = new HashSet<Supplier>();
            Suppliers2 = new HashSet<Supplier>();
            SupplierTransactions = new HashSet<SupplierTransaction>();
            BuyingGroups = new HashSet<BuyingGroup>();
            CustomerCategories = new HashSet<CustomerCategory>();
            Customers = new HashSet<Customer>();
            Customers1 = new HashSet<Customer>();
            Customers2 = new HashSet<Customer>();
            CustomerTransactions = new HashSet<CustomerTransaction>();
            InvoiceLines = new HashSet<InvoiceLine>();
            Invoices = new HashSet<Invoice>();
            Invoices1 = new HashSet<Invoice>();
            Invoices2 = new HashSet<Invoice>();
            Invoices3 = new HashSet<Invoice>();
            Invoices4 = new HashSet<Invoice>();
            OrderLines = new HashSet<OrderLine>();
            Orders = new HashSet<Order>();
            Orders1 = new HashSet<Order>();
            Orders2 = new HashSet<Order>();
            Orders3 = new HashSet<Order>();
            SpecialDeals = new HashSet<SpecialDeal>();
            Colors = new HashSet<Color>();
            PackageTypes = new HashSet<PackageType>();
            StockGroups = new HashSet<StockGroup>();
            StockItemHoldings = new HashSet<StockItemHolding>();
            StockItems = new HashSet<StockItem>();
            StockItemStockGroups = new HashSet<StockItemStockGroup>();
            StockItemTransactions = new HashSet<StockItemTransaction>();
        }


        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int PersonID { get; set; }

        [Required]
        [StringLength(50)]
        [DisplayName("Full Name:")]
        public string FullName { get; set; }

        [Required]
        [StringLength(50)]
        [DisplayName("Preferred Name:")]
        public string PreferredName { get; set; }

        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        [Required]
        [StringLength(101)]
        public string SearchName { get; set; }

        public bool IsPermittedToLogon { get; set; }

        [StringLength(50)]
        public string LogonName { get; set; }

        public bool IsExternalLogonProvider { get; set; }

        public byte[] HashedPassword { get; set; }

        public bool IsSystemUser { get; set; }

        public bool IsEmployee { get; set; }

        public bool IsSalesperson { get; set; }

        public string UserPreferences { get; set; }

        [StringLength(20)]
        [DisplayName("Phone Number:")]
        public string PhoneNumber { get; set; }

        [StringLength(20)]
        [DisplayName("Fax Number:")]
        public string FaxNumber { get; set; }

        [StringLength(256)]
        [DisplayName("Email Address:")]
        public string EmailAddress { get; set; }

        public byte[] Photo { get; set; }

        public string CustomFields { get; set; }

        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public string OtherLanguages { get; set; }

        public int LastEditedBy { get; set; }

        [Column(TypeName = "datetime2")]
        [DisplayName("Member Since:")]
        public DateTime ValidFrom { get; set; }

        [Column(TypeName = "datetime2")]
        public DateTime ValidTo { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<City> Cities { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Country> Countries { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeliveryMethod> DeliveryMethods { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentMethod> PaymentMethods { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Person> People1 { get; set; }

        public virtual Person Person1 { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StateProvince> StateProvinces { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SystemParameter> SystemParameters { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionType> TransactionTypes { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrderLine> PurchaseOrderLines { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrder> PurchaseOrders { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrder> PurchaseOrders1 { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplierCategory> SupplierCategories { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Supplier> Suppliers { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Supplier> Suppliers1 { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Supplier> Suppliers2 { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplierTransaction> SupplierTransactions { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BuyingGroup> BuyingGroups { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerCategory> CustomerCategories { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer> Customers { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer> Customers1 { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer> Customers2 { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerTransaction> CustomerTransactions { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceLine> InvoiceLines { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice> Invoices { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice> Invoices1 { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice> Invoices2 { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice> Invoices3 { get; set; }

HW6/WorldWideImporter/WorldWideImporter/Controllers/PeopleController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Diagnostics;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WorldWideImporter.Models;
using WorldWideImporter.Models.CompanyViewModel;

namespace WorldWideImporter.Controllers
{
    public class PeopleController : Controller
    {
        /// <summary>
        /// This is the context file that connects my db to the project
        /// </summary>
        private WWIContext db = new WWIContext();

        /// <summary>
        /// This searches for the users in the db
        /// </summary>
        /// <param name="search">the string that is entered to look through the db</param>
        /// <returns>a view with a person that matches the query string</returns>
        // GET: People
        public ActionResult Index(String search)
        {
            //Using my View Model
            ViewModel vm = new ViewModel();


            search = Request.QueryString["search"];
            if (search == null || search == "")
            {
                ViewBag.show = false;
                return View();
            }
            else
            {
                ViewBag.show = true;
                return View(db.People.Where(p => p.FullName.Contains(search)).ToList());
            }
        }

        /// <summary>
        /// This retrieves the information concerning the person
        /// </summary>
        /// <param name="id">takes in an id, then matches the person</param>
        /// <returns>the ViewModel with PErson, Customer, and InvoiceLines</returns>
        // GET: People/Details/5
        public ActionResult Details(int? id)
        {
            //my viewmodel
            ViewModel vm = new ViewModel();

            //find the person
            vm.Person = db.People.Find(id);

            //if he is a regular person lets not show anymore information
            ViewBag.IsP = false;

            //if he is a primary contact person
            if (vm.Person.Customers2.Count() > 0)
            {
                //lets show the information
                ViewBag.IsP = true;
                int cid = vm.Person.Customers2.FirstOrDefault().CustomerID;
                vm.Customer = db.Customers.Find(cid);

                //find the gross sales
                ViewBag.GrossSales = vm.Customer.Orders.SelectMany(il => il.Invoices).SelectMany(ils => ils.InvoiceLines).Sum(i => i.ExtendedPrice);

                //find the gross profit
                ViewBag.GrossProfit = vm.Customer.Orders.SelectMany(il => il.Invoices).SelectMany(ils => ils.InvoiceLines).Sum(i => i.LineProfit);

                //selects the information on the top ten sales
                vm.InvoiceLine = vm.Customer.Orders.SelectMany(x => x.Invoices)
                                                .SelectMany(i => i.InvoiceLines)
                                                .OrderByDescending(i => i.LineProfit)
                                                .Take(10)
                                                .ToList();

            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Person person = db.People.Find(id);
            if (person == null)
            {
                return HttpNotFound();
            }
            return View(vm);
        }

    }
}

HW6/WorldWideImporter/WorldWideImporter/Views/People/Details.cshtml
@model WorldWideImporter.Models.CompanyViewModel.ViewModel

@{
    ViewBag.Title = "Details";
}
<head>
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.4/dist/leaflet.css"
          integrity="sha512-puBpdR0798OZvTTbP4A8Ix/l+A4dHDD0DGqYW6RQ+9jxkRFclaxxQb/SJAWZfWAkuyeQUytO7+7N4QKrDh+drA=="
          crossorigin="" />
    <!-- Leaflet's JS for use with MapBox -->
    <script src="https://unpkg.com/leaflet@1.3.4/dist/leaflet.js"
            integrity="sha512-nMMmRyTVoLYqjP9hrbed9S+FzjZHW5gY1TWCHA5ckwXZBadntCNs8kEqAWdrb9O7rxbCaA4lKTIWjDXZxflOcA=="
            crossorigin=""></script>
</head>
<div class="row page-header">
    <img src="~/Content/banner4.jpg" height="200" width="1170" />
</div>

@*This View displays all the infrormation about the person including the person basic information, and if he is a primary contact sales person, shows about his company and his top ten sales*@

<h2>Details</h2>

<div>

    <hr />

    <div class="row">

        <div class="col-md-3">
            <img src="https://via.placeholder.com/250" alt="@Model.Person.Photo" />
        </div>

        <div class="col-md-7">
            <div id="person-description">

                <h3 id="person-subcat">@Model.Person.FullName</h3>
                <dl class="dl-horizontal">

                    <dt>
                        @Html.Label("preferred-name", "Preferred Name:")
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Person.PreferredName)
                    </dd>

                    <dt>
                        @Html.Label("phone-number", "Phone Number:")
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Person.PhoneNumber)
                    </dd>

                    <dt>
                        @Html.Label("fax-number", "Fax Number:")
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Person.FaxNumber)
                    </dd>

                    <dt>
                        @Html.Label("email-address", "Email Address:")
                    </dt>

                    <dd>
                        <a href="mailto:@Html.DisplayFor(model => model.Person.EmailAddress)">@Html.DisplayFor(model => model.Person.EmailAddress)</a>
                    </dd>

                    <dt>
                        @Html.Label("member-since", "Member Since:")
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Person.ValidFrom)
                    </dd>

                </dl>
            </div>

            <br />
            @if (ViewBag.IsP)
            {

                <div id="person-description">

                    <h3 id="person-subcat">Company Profile</h3>

                    <dl class="dl-horizontal">

                        <dt>
                            @Html.Label("customer-name", "Customer Name:")
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Customer.CustomerName)
                        </dd>

                        <dt>
                            @Html.Label("phone-number", "Phone Number:")
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Customer.PhoneNumber)
                        </dd>

                        <dt>
                            @Html.Label("fax-number", "Fax Number:")
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Customer.FaxNumber)
                        </dd>

                        <dt>
                            @Html.Label("website-url", "Website URL:")
                        </dt>

                        <dd>
                            <a href="@Model.Customer.WebsiteURL">@Html.DisplayFor(model => model.Customer.WebsiteURL)</a>
                        </dd>

                        <dt>
                            @Html.Label("member-since", "Member Since:")
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Customer.ValidFrom)
                        </dd>


                    </dl>


                </div>

                <br />
                <div id="person-description">

                    <h3 id="person-subcat">Purchase History Summary</h3>

                    <dl class="dl-horizontal">

                        <dt>
                            @Html.Label("order-count", "Count:")
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Customer.Orders.Count)
                        </dd>

                        <dt>
                            @Html.Label("gross-sales", "Gross Sales:")
                        </dt>

                        <dd>
                            @String.Format("{0:C}", ViewBag.GrossSales)
                        </dd>

                        <dt>
                            @Html.Label("gross-profit", "Gross Profit:")
                        </dt>

                        <dd>
                            @String.Format("{0:C}", ViewBag.GrossProfit)
                        </dd>

                    </dl>

                </div>

                <br />

                <div id="person-description">
                    <h3 id="person-subcat">Items Purchased</h3>
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">
                                    @Html.Label("stock-item", "Stock Item ID")
                                </th>

                                <th scope="col">
                                    @Html.Label("description", "Description")
                                </th>

                                <th scope="col">
                                    @Html.Label("line-profit", "Line Profit")
                                </th>

                                <th scope="col">
                                    @Html.Label("sales-person", "Sales Person")
                                </th>
                            </tr>
                        </thead>

                        @foreach (var items in Model.InvoiceLine)
                        {
                            <tbody>
                                <tr>

                                    <td>
                                        @Html.DisplayFor(item => items.StockItemID)
                                    </td>

                                    <td>
                                        @Html.DisplayFor(item => items.Description)
                                    </td>

                                    <td>
                                        @String.Format("{0:C}", items.LineProfit)
                                    </td>

                                    <td>
                                        @Html.DisplayFor(item => items.Invoice.Person4.FullName)
                                    </td>

                                </tr>

                            </tbody>

                        }


                    </table>
                </div>

                <div id="person-description">
                    <div id="map" style="width:647px; height:300px;"> </div>
                    <script>
                            var long = @Model.Customer.DeliveryLocation.Longitude;
                            var lat = @Model.Customer.DeliveryLocation.Latitude;

                            var map = L.map('map').setView([lat, long], 15);

                            L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
                                attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
                            }).addTo(map);

                            L.marker([lat, long]).addTo(map)
                                .bindPopup('<p>' + @Model.Customer.City.CityName + '</p>').openPopup();





                    </script>

                </div>



            }

        </div>

    </div>




</div>

<br />



<div>
    <p>
        @Html.ActionLink("Back to Search", "Index")
    </p>
</div>

HW6/WorldWideImporter/WorldWideImporter/Views/People/Index.cshtml
@model IEnumerable<WorldWideImporter.Models.Person>

@{
    ViewBag.Title = "Index";
}

@*This View is the searching function of the controller, it takes the string and passes back to the controller, uses a person model*@

<div class="row page-header">
    <img src="~/Content/banner4.jpg" height="200" width="1170" />
</div>

<h2 id="title">Client Search</h2>

@using (Html.BeginForm("Index", "People", FormMethod.Get, new { @class = "form-inline" }))
{<br />

    <div class="form-group">
        <div class="input-group">

            @Html.TextBox("search", "", new { @class = "form-control", @id = "people-search", @placeholder = "Enter Client Name", required = "required" })
            <span class="input-group-btn">
                <button class="btn btn-default " type="submit"><span class="glyphicon glyphicon-search"></span></button>
            </span>

        </div>
    </div>
}

@if (ViewBag.show)
{
    <br />
    if (Model.Count() == 0)
    {
        <h4 style="color:red">Sorry Couldn't Find a Match</h4>

    }
    else
    {
        <div>
            <h4>Client Name:</h4>
        </div>
        <br />
        foreach (var person in Model)
        {
            <div>


                <a class="btn btn-default btn-lg btn-block" href="People/Details/@person.PersonID" role="button">@person.FullName (@person.PreferredName)</a>
            </div>
        }
    }
}


@section myjs
{
    <script type="text/javascript" src="@Url.Content("/Scripts/AJAX.js")"></script>
}