HW5/Campus-Applications/Campus-Applications/Models/Request.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Campus_Applications.Models
{
    public class Request
    {
        /// <summary>
        /// Key 
        /// </summary>
        public int ID { get; set; }

        //Data Attributtes
        /// <summary>
        /// First name of the tenant 
        /// </summary>
        [Required(ErrorMessage = "First Name is Required")]
        [DisplayName("First Name:")]
        public string FirstName { get; set; }

        /// <summary>
        /// Last name of the tenant
        /// </summary>
        [Required(ErrorMessage = "Last Name is Required")]
        [DisplayName("Last Name:")]
        public string LastName { get; set; }

        /// <summary>
        /// Phone number of the person requesting help
        /// </summary>
        [Required(ErrorMessage = "Phone Number is Required")]
        [DisplayName("Phone Number:")]
        [RegularExpression(@"^[2-9]\d{2}-\d{3}-\d{4}$", ErrorMessage = "Please use the format: XXX-XXX-XXXX")]
        public string PhoneNumber { get; set; }

        /// <summary>
        /// user or the tenants apartment name
        /// </summary>
        [Required(ErrorMessage = "Apartment Name is Required")]
        [DisplayName("Apartment Name:")]
        public string ApartmentName { get; set; }

        /// <summary>
        /// This is the description of the problem
        /// </summary>
        [Required(ErrorMessage = "A Description is Required")]
        [DisplayName("Problem Description:")]
        public string Explanation { get; set; }

        /// <summary>
        /// This is the unit number of the aparment
        /// </summary>
        [Required(ErrorMessage = "Unit Number is Required")]
        [DisplayName("Unit Number:")]
        public int UnitNumber { get; set; }

        /// <summary>
        /// This is the checkbox that is selected if the users give permission to the owners to enter
        /// </summary>
        [DisplayName("Permission to enter unit to perform request:")]
        public bool CallMe { get; set; }

        /// <summary>
        /// Stamps the form with the current date and time
        /// </summary>
        private DateTime date = DateTime.Now;
        [DisplayName("Submittion Date:")]
        public DateTime SignedDate
        {
            get { return date; }
            set { date = value; }
        }
    }
  
}

HW5/Campus-Applications/Campus-Applications/Controllers/RequestsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Campus_Applications.DAL;
using Campus_Applications.Models;

namespace Campus_Applications.Controllers
{
    public class RequestsController : Controller
    {
        private RequestdbContext db = new RequestdbContext();

        /// <summary>
        /// This is the list of all the requests that have been entered into the form
        /// </summary>
        /// <returns>the view in order of the signed date</returns>
        // GET: Requests
        public ActionResult Index()
        {
            return View(db.Requests.ToList().OrderBy(x => x.SignedDate));
        }

        /// <summary>
        /// This is the homepage or the welcome page of the form
        /// </summary>
        /// <returns>view of the homepage</returns>
        public ActionResult Home()
        {
            return View();
        }



        /// <summary>
        /// This is the GET form of the create before the form is submitted
        /// </summary>
        /// <returns>the view of the GET version of the create</returns>
        // GET: Requests/Create
        public ActionResult Create()
        {
            return View();
        }

        /// <summary>
        /// This is the POST version of create, which takes all the form inputs and places it in the dB
        /// </summary>
        /// <param name="request">places the all the paramteres into the model</param>
        /// <returns>redirects to the list that has all the list of requests</returns>
        // POST: Requests/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,FirstName,LastName,PhoneNumber,ApartmentName,Explanation,UnitNumber,CallMe,SignedDate")] Request request)
        {
            if (ModelState.IsValid)
            {
                db.Requests.Add(request); //stages it
                db.SaveChanges(); //Fully commits to database
                return RedirectToAction("Index");
            }

            return View(request);
        }


    }

  
}

HW5/Campus-Applications/Campus-Applications/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

HW5/Campus-Applications/Campus-Applications/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

HW5/Campus-Applications/Campus-Applications/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

HW5/Campus-Applications/Campus-Applications/Views/Requests/Create.cshtml
@model Campus_Applications.Models.Request

@{
    ViewBag.Title = "Create";
}

<h1 id="title">Campus Apartments</h1>
<h3 id="sub-title">Tenant Request</h3>
<br />
<br />
@*This is the Form that uses razor and is strongly typed *@
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="container">

        <div class="form-group col-md-4">
            @Html.LabelFor(model => model.FirstName)
            @Html.TextBoxFor(model => model.FirstName, "", new { @class = "form-control", @placeholder = "Enter First Name" })
            @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
        </div>

        <div class="form-group col-md-4">
            @Html.LabelFor(model => model.LastName)
            @Html.TextBoxFor(model => model.LastName, "", new { @class = "form-control", @placeholder = "Enter Last Name" })
            @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
        </div>

        <div class="form-group col-md-4">
            @Html.LabelFor(model => model.PhoneNumber)
            @Html.TextBoxFor(model => model.PhoneNumber, "", new { @class = "form-control", @placeholder = "Enter Phone Number Here" })
            @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
        </div>
        <br />

    </div>

    <div class="container">
        <div class="form-group col-md-6">
            @Html.LabelFor(model => model.ApartmentName)
            @Html.TextBoxFor(model => model.ApartmentName, "", new { @class = "form-control", @placeholder = "Enter Apartment Name" })
            @Html.ValidationMessageFor(model => model.ApartmentName, "", new { @class = "text-danger" })
        </div>

        <div class="form-group col-md-6">
            @Html.LabelFor(model => model.UnitNumber)
            @Html.TextBoxFor(model => model.UnitNumber, "", new { @class = "form-control", @placeholder = "Enter Unit Number" })
            @Html.ValidationMessageFor(model => model.UnitNumber, "", new { @class = "text-danger" })
        </div>



    </div>

    <div class="container">
        <div class="form-group col-md-12">
            @Html.LabelFor(model => model.Explanation)
            @Html.TextAreaFor(model => model.Explanation, new { @class = "form-control", @rows = 10, placeholder = "Enter Problem Description" })
            @Html.ValidationMessageFor(model => model.Explanation, "", new { @class = "text-danger" })
        </div>



    </div>

    <div class="container">
        <div class="form-group col-md-4">

            @Html.LabelFor(model => model.CallMe)
            @Html.CheckBoxFor(model => model.CallMe)

        </div>

        <br />
        <br />

        
        <button type="submit" class="btn btn-primary btn-lg btn-block">Submit Request</button>
        

    </div>


    <br />
    



}



<div>
    @Html.ActionLink("Back to List", "Index")
</div>

HW5/Campus-Applications/Campus-Applications/Views/Requests/Home.cshtml
@{
    ViewBag.Title = "Home";
}

<br />
<!--Welcome page for the users-->
<div class="jumbotron">
    <h1>Welcome to Campus Apartments</h1>
    <br />
    <p class="lead">Your roomate broke your refigerator, or your wall fell on you, and you don't know what to do? Before you go to BestBuy and purchase another refrigerator for about $900, or ducktape the wall together, let our experts make an effort. All you have to do is fill in the application linked down below.</p>
    
    <p><a href="Create" class="btn btn-primary btn-lg">Fill Out Form &raquo;</a></p>
</div>

HW5/Campus-Applications/Campus-Applications/Views/Requests/Index.cshtml
@model IEnumerable<Campus_Applications.Models.Request>

@{
    ViewBag.Title = "Index";
}

<h2>Current Requests</h2>
<br />
@*This is the View which is also stronlgy typed and is ordered by the time is was submitted*@
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ApartmentName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Explanation)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UnitNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CallMe)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SignedDate)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PhoneNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ApartmentName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Explanation)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UnitNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CallMe)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SignedDate)
        </td>
        

    </tr>

       
    }



</table>

HW5/Campus-Applications/Campus-Applications/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Campus Apartments", "Home", "Requests", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Current Requests", "Index", "Requests")</li>
                    <li>@Html.ActionLink("New Requests", "Create", "Requests")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Shion Wakita</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>